BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET

blogger_blog_blog_show:
    path:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

blogger_blog_create_show:
    path:  /create
    defaults: { _controller: BloggerBlogBundle:Blog:create }
    requirements:
        _method:  GET

blogger_blog_blog_edit:
    path:  /edit/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:edit }
    requirements:
        _method:  GET