<?php

namespace Blogger\BlogBundle\Entity;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAuthors($limit = null)
    {
        $qb = $this->createQueryBuilder('a')
               ->select('a', 'b')
               ->join('a.blogs', 'b')
               ->addOrderBy('a.dataAlta', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
