<?php

namespace Blogger\BlogBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTagsCol(){
		$em = $this->getEntityManager();
		 
		$qb = $em->createQuery('SELECT t.tagName as name, COUNT(t.id) as num FROM Blogger\BlogBundle\Entity\Tag t JOIN t.blogs b GROUP BY t.id');
		$blogTags = $qb->getResult();

		$tagWeights = array();
		foreach ($blogTags as $tag){
			$tagWeights[$tag['name']] = $tag['num'];
      	}

		// Revuelve las etiquetas
		uksort($tagWeights, function() {
		  return rand() > rand();
		});
		$max = max($tagWeights);
		// un peso máximo de 5
		$multiplier = ($max > 5) ? 5 / $max : 1;
		foreach ($tagWeights as &$tag)
		{
		  $tag = ceil($tag * $multiplier);
		}
		return $tagWeights;

		/*$query = $em->createQuery('SELECT t, count(b.id) FROM Tag t JOIN t.Blog b GROUP BY t.id');
		$result = $query->getResult();*/
	    /*
		SELECT t.tag_name, COUNT(t.id) num
		FROM `TAG` t
		INNER JOIN `BLOGS_TAGS` bt
		ON t.id = bt.tag_id
		GROUP BY (t.id)
	    */
    }
}
